name: ToolStats
description: Collect stats of using tool
main: pro.eugw.ToolStats.Main
version: 3.1
author: EugeneWhite
commands:
  toolstats:
    description: Reload
    usage: /toolstats
permissions:
  toolstats.reload:
    description: Reload permission
    default: op
  toolstats.counter:
    description: Allow counter
    default: op
  toolstats.upgrade:
    description: Allow upgrade
    default: op