name: ToolStats
description: Collect stats of using tool
main: pro.eugw.toolstats.Main
version: '4.7.1'
api-version: '1.16'
author: EugeneWhite(EugW)
commands:
  toolstats:
    description: Reload plugin config
    usage: /toolstats
  tstracking:
    description: Starts - stops tracking
    usage: /tstracking (only >1.7)[break|killPlayer|killMob] [start|stop]
  tsclearlore:
    description: Use if you're server own changed Lore line in config, will not reset counter
    usage: /tsclearlore
permissions:
  toolstats.reload:
    description: Reload permission
    default: op
  toolstats.counter:
    description: Allow counter
    default: op
  toolstats.upgrade:
    description: Allow upgrade
    default: op
  toolstats.tstracking:
    description: Allow start/stop tracking
    default: op
  toolstats.tsclearlore:
    description: Allow clearing item Lore
    default: op