name: ToolStats
description: Collect stats of using tool
main: pro.eugw.toolstats.Main
version: '4.7'
api-version: '1.16'
author: EugeneWhite(EugW)
commands:
  toolstats:
    description: Reload
    usage: /toolstats
  tstracking:
    description: Starts - stops tracking
    usage: /tstracking [start|stop]
permissions:
  toolstats.reload:
    description: Reload permission
    default: op
  toolstats.counter:
    description: Allow counter
    default: op
  toolstats.upgrade:
    description: Allow upgrade
    default: op
  toolstats.tstracking:
    description: Allow start/stop tracking
    default: op